project:
  type: website

website:
  title: "Winfred Dotse-Gborgbortsi"
  navbar:
    background: info
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Winfred
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: consultancy.qmd
        text: Consultancy
      - href: blogposts/index.qmd
        text: Blog
      - href: contact.qmd
        text: Contact
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

